// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.2
// source: future/future.proto

package future

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/relab/gorums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Request1) Reset() {
	*x = Request1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_future_future_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request1) ProtoMessage() {}

func (x *Request1) ProtoReflect() protoreflect.Message {
	mi := &file_future_future_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request1.ProtoReflect.Descriptor instead.
func (*Request1) Descriptor() ([]byte, []int) {
	return file_future_future_proto_rawDescGZIP(), []int{0}
}

type Request2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Request2) Reset() {
	*x = Request2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_future_future_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request2) ProtoMessage() {}

func (x *Request2) ProtoReflect() protoreflect.Message {
	mi := &file_future_future_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request2.ProtoReflect.Descriptor instead.
func (*Request2) Descriptor() ([]byte, []int) {
	return file_future_future_proto_rawDescGZIP(), []int{1}
}

type Response1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Response1) Reset() {
	*x = Response1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_future_future_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response1) ProtoMessage() {}

func (x *Response1) ProtoReflect() protoreflect.Message {
	mi := &file_future_future_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response1.ProtoReflect.Descriptor instead.
func (*Response1) Descriptor() ([]byte, []int) {
	return file_future_future_proto_rawDescGZIP(), []int{2}
}

type Response2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Response2) Reset() {
	*x = Response2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_future_future_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response2) ProtoMessage() {}

func (x *Response2) ProtoReflect() protoreflect.Message {
	mi := &file_future_future_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response2.ProtoReflect.Descriptor instead.
func (*Response2) Descriptor() ([]byte, []int) {
	return file_future_future_proto_rawDescGZIP(), []int{3}
}

var File_future_future_proto protoreflect.FileDescriptor

var file_future_future_proto_rawDesc = []byte{
	0x0a, 0x13, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x1a, 0x0c, 0x67,
	0x6f, 0x72, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0a, 0x0a, 0x08, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x31, 0x22, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x32, 0x22, 0x0b, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x31,
	0x22, 0x0b, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x32, 0x8c, 0x01,
	0x0a, 0x0a, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x54, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x09,
	0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x51, 0x43, 0x31, 0x12, 0x10, 0x2e, 0x66, 0x75, 0x74, 0x75,
	0x72, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x31, 0x1a, 0x11, 0x2e, 0x66, 0x75,
	0x74, 0x75, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x31, 0x22, 0x0c,
	0x80, 0xb5, 0x18, 0x01, 0x90, 0xb5, 0x18, 0x01, 0x88, 0xb5, 0x18, 0x01, 0x12, 0x3e, 0x0a, 0x09,
	0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x51, 0x43, 0x32, 0x12, 0x10, 0x2e, 0x66, 0x75, 0x74, 0x75,
	0x72, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0x1a, 0x11, 0x2e, 0x66, 0x75,
	0x74, 0x75, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x22, 0x0c,
	0x80, 0xb5, 0x18, 0x01, 0x90, 0xb5, 0x18, 0x01, 0x88, 0xb5, 0x18, 0x01, 0x42, 0x26, 0x5a, 0x24,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x62,
	0x2f, 0x67, 0x6f, 0x72, 0x75, 0x6d, 0x73, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x66, 0x75,
	0x74, 0x75, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_future_future_proto_rawDescOnce sync.Once
	file_future_future_proto_rawDescData = file_future_future_proto_rawDesc
)

func file_future_future_proto_rawDescGZIP() []byte {
	file_future_future_proto_rawDescOnce.Do(func() {
		file_future_future_proto_rawDescData = protoimpl.X.CompressGZIP(file_future_future_proto_rawDescData)
	})
	return file_future_future_proto_rawDescData
}

var file_future_future_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_future_future_proto_goTypes = []interface{}{
	(*Request1)(nil),  // 0: future.Request1
	(*Request2)(nil),  // 1: future.Request2
	(*Response1)(nil), // 2: future.Response1
	(*Response2)(nil), // 3: future.Response2
}
var file_future_future_proto_depIdxs = []int32{
	0, // 0: future.FutureTest.FutureQC1:input_type -> future.Request1
	1, // 1: future.FutureTest.FutureQC2:input_type -> future.Request2
	2, // 2: future.FutureTest.FutureQC1:output_type -> future.Response1
	3, // 3: future.FutureTest.FutureQC2:output_type -> future.Response2
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_future_future_proto_init() }
func file_future_future_proto_init() {
	if File_future_future_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_future_future_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_future_future_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_future_future_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_future_future_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_future_future_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_future_future_proto_goTypes,
		DependencyIndexes: file_future_future_proto_depIdxs,
		MessageInfos:      file_future_future_proto_msgTypes,
	}.Build()
	File_future_future_proto = out.File
	file_future_future_proto_rawDesc = nil
	file_future_future_proto_goTypes = nil
	file_future_future_proto_depIdxs = nil
}
