// Code generated by protoc-gen-gorums. DO NOT EDIT.

package dev

import (
	sync "sync"
)

type managerData struct {
	readOrderedID   uint64
	readOrderedRecv map[uint64]chan *internalReadResponse
	readOrderedLock sync.RWMutex
}

func newManagerData() *managerData {
	return &managerData{
		readOrderedRecv: make(map[uint64]chan *internalReadResponse),
	}
}

func (m *managerData) createNodeData() *nodeData {
	return &nodeData{
		readOrderedSend: make(chan *ReadRequest, 1),
		readOrderedRecv: m.readOrderedRecv,
		readOrderedLock: &m.readOrderedLock,
	}
}
