// Code generated by protoc-gen-gorums. DO NOT EDIT.

package dev

import (
	sync "sync"
)

type managerData struct {
	strictOrderingID   uint64
	strictOrderingRecv map[uint64]chan *internalResponse
	strictOrderingLock sync.RWMutex
}

func newManagerData() *managerData {
	return &managerData{
		strictOrderingRecv: make(map[uint64]chan *internalResponse),
	}
}

func (m *managerData) createNodeData() *nodeData {
	return &nodeData{
		strictOrderingSend:    make(chan *Request, 1),
		strictOrderingRecv:    m.strictOrderingRecv,
		strictOrderingMapLock: &m.strictOrderingLock,
	}
}
